
create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  device_id text not null unique,
  minion_name text,
  subscription jsonb not null,
  is_host boolean not null default false,
  updated_at timestamptz not null default now()
);

alter table public.push_subscriptions enable row level security;

drop policy if exists "Anyone can insert push subscriptions" on public.push_subscriptions;
drop policy if exists "Anyone can update push subscriptions" on public.push_subscriptions;
drop policy if exists "Anyone can view push subscriptions during development" on public.push_subscriptions;

create policy "Anyone can insert push subscriptions"
on public.push_subscriptions for insert with check (true);

create policy "Anyone can update push subscriptions"
on public.push_subscriptions for update using (true) with check (true);

create policy "Anyone can view push subscriptions during development"
on public.push_subscriptions for select using (true);
